### ISSUE TITLE
Error- Failed to install gotests dependencies

### ISSUE THREAD

**Issue by michael-gracy** [abulimov/atom-gotests#2]
This is popping up with every startup. Here are the relevant entries from the Atom console:
/Users/michael.gracy/.atom/packages/gotests/node_modules/atom-package-deps/lib/view.js:69 [Package-Deps] Unable to install go-config , Error: Request for package information failed: Not Foundcomplete @ /Users/michael.gracy/.atom/packages/gotests/node_modules/atom-package-deps/lib/view.js:69
/Users/michael.gracy/.atom/packages/gotests/node_modules/atom-package-deps/lib/view.js:69 [Package-Deps] Unable to install go-get , Error: Request for package information failed: Not Foundcomplete @ /Users/michael.gracy/.atom/packages/gotests/node_modules/atom-package-deps/lib/view.js:69

**Comment by abulimov** [comment]
Thanks for reporting, I'll take a look this week.

**Comment by abulimov** [comment]
What operating system are you using? And what atom version? I've checked on MacOS with latest Atom 1.12.7 - all fine.

**Comment by michael-gracy** [comment]
I am on OSX 10.11.6 with Atom 1.12.7.
Here is the output of apm list:
02:46 $ apm list
Built-in Atom Packages (89)
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.52.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.45.0
├── base16-tomorrow-dark-theme@1.3.0
├── base16-tomorrow-light-theme@1.3.0
├── one-dark-ui@1.6.2
├── one-light-ui@1.6.2
├── one-dark-syntax@1.5.0
├── one-light-syntax@1.5.0
├── solarized-dark-syntax@1.0.5
├── solarized-light-syntax@1.0.5
├── about@1.7.0
├── archive-view@0.62.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.13.1
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.31.4
├── autocomplete-snippets@1.11.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.1
├── bookmarks@0.42.0
├── bracket-matcher@0.82.2
├── command-palette@0.39.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.22.0
├── exception-reporting@0.40.0
├── find-and-replace@0.202.2
├── fuzzy-finder@1.4.0
├── git-diff@1.1.0
├── go-to-line@0.31.0
├── grammar-selector@0.48.2
├── image-view@0.60.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── line-ending-selector@0.5.0
├── link@0.31.2
├── markdown-preview@0.158.8
├── metrics@1.1.2
├── notifications@0.65.1
├── open-on-github@1.2.1
├── package-generator@1.0.1
├── settings-view@0.243.1
├── snippets@1.0.4
├── spell-check@0.68.4
├── status-bar@1.4.1
├── styleguide@0.47.2
├── symbols-view@0.113.1
├── tabs@0.103.0
├── timecop@0.33.2
├── tree-view@0.210.0
├── update-package-dependencies@0.10.0
├── welcome@0.35.1
├── whitespace@0.35.0
├── wrap-guide@0.38.2
├── language-c@0.54.0
├── language-clojure@0.22.1
├── language-coffee-script@0.48.0
├── language-csharp@0.13.0
├── language-css@0.40.1
├── language-gfm@0.88.0
├── language-git@0.15.0
├── language-go@0.43.0
├── language-html@0.47.1
├── language-hyperlink@0.16.1
├── language-java@0.24.0
├── language-javascript@0.122.0
├── language-json@0.18.3
├── language-less@0.29.6
├── language-make@0.22.2
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.37.3
├── language-property-list@0.8.0
├── language-python@0.45.1
├── language-ruby@0.70.2
├── language-ruby-on-rails@0.25.1
├── language-sass@0.57.0
├── language-shellscript@0.23.0
├── language-source@0.9.0
├── language-sql@0.25.0
├── language-text@0.7.1
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.34.12
└── language-yaml@0.27.1

Community Packages (52) /Users/michael.gracy/.atom/packages
├── atom-beautify@0.29.14
├── atom-keyboard-macros@0.9.2
├── autocomplete-ansible@0.1.10
├── autocomplete-bash-builtins@0.3.4
├── autocomplete-json@5.2.0
├── autocomplete-python@1.8.24
├── block-comment@0.4.3
├── config-import-export@0.3.1
├── dash@1.7.0
├── dash-on-cursor-active@0.1.2
├── file-types@0.5.4-p1
├── git-blame@0.4.11
├── git-plus@6.3.0
├── git-time-machine@1.5.4
├── go-debug@1.0.0
├── go-plus@5.0.7
├── go-signature-statusbar@1.2.0
├── gotests@0.2.5
├── hyperclick@0.0.39
├── json-colorer@0.3.0
├── json-generator@0.1.15
├── jsonlint@1.1.4
├── language-ansible@0.1.11
├── language-markdown@0.18.1
├── language-powershell@4.0.0
├── language-puppet@0.21.0
├── linter@1.11.18
├── linter-ansible-linting@1.2.1
├── linter-checkbashisms@0.1.5
├── linter-markdown@3.0.2
├── linter-puppet-lint@0.8.1
├── linter-python-pep8@0.2.0
├── linter-shellcheck@1.4.2
├── lipsum@0.1.0
├── markdown-pdf@1.5.0
├── markdown-preview-plus@2.4.0
├── markdown-scroll-sync@2.1.2
├── markdown-writer@2.6.2
├── overlay-status-icons@0.1.6
├── project-manager@3.3.3
├── python-debugger@0.1.0
├── python-indent@1.0.0
├── python-nosetests@0.2.0
├── python-tools@0.6.8
├── qolor@0.4.1
├── save-session@0.15.7
├── script@3.13.0
├── ssh-config@0.10.1
├── svn@0.0.13
├── terminal-plus@0.14.5
├── tool-bar@1.0.1
└── tool-bar-atom@1.7.0

└── (empty)

I don't know why that empty line is there near the bottom <shrug>

**Comment by trenton42** [comment]
I think the issues is that `go-config` and `go-get` were consolidated into `go-plus` in [this release](https://github.com/joefitzgerald/go-plus/releases/tag/v5.0.0)

**Comment by Nicolab** [comment]
Hello,

With the last version of go-plus (5.0.9, updated today), I have the same issue in Atom 1.12.7 on Ubuntu 16.04.

**Comment by trenton42** [comment]
@abulimov Thanks for fixing it! 👍

**Comment by michael-gracy** [comment]
Thank you! 👍

**Comment by Nicolab** [comment]
Thanks :+1:
